### PR TITLE
Add ZarrService

### PR DESCRIPTION
**Pull request by dgault**
Required for testing of ongoing Zarr reader and writer work

### CODE REVIEW

**Comment by sbesson** [comment]
From Travis CI

```
+./minio version
‘version’ is not a minio sub-command. See ‘minio --help’.
The command "cd location-server && ./start-location.sh && cd .." failed and exited with 1 during .
```

This probably brings us back to the discussion in https://github.com/ome/ome-common-java/pull/47#issuecomment-519875659

**Comment by sbesson** [comment]
Once the Travis CI issue is fixed, should we release this immediately as a patch or minor release increment? This might be required to allow https://github.com/ome/bioformats/pull/3554 to pass Travis and be included in the daily CI build /cc @joshmoore @jburel

**Comment by dgault** [comment]
I dont know about releasing it since this is very much a prototype for testing purposes only. I can hardcode the BF PR to just use the ZarrServiceImpl directly if that is easier for getting it into the daily merge build

**Comment by sbesson** [comment]
Understood. :+1: for hard coding the service implementation in the Bio-Formats PR to get this easily deployed and tested for now.

**Pull request closed without merging**
